data2 = read.table("wrinkle.txt", header = T)
summary(data2)
hist(data2$press)
par(mfrow = c(1,4))
hist(data2$HCHO)
hist(data2$catalyst)
hist(data2$temp)
hist(data2$time)
pairs(data2)

gfit = lm(press ~ HCHO+catalyst+temp+time, data2)
summary(gfit)
