train_data = read.csv("train.csv")
View(train_data)
dim(train_data)
test_data = read.csv("test.csv")

mod1 = lm(y+2.8 ~ x1+x2, train_data)
summary(mod1)
par(mfrow = c(2,2))
plot(mod1)
rstud = rstandard(mod1)
plot(mod1$fitted.values,rstud)
plot(train_data$x1,rstud)
plot(train_data$x2,rstud)

mod2 = update(mod1, .~.+I(x2^2))
summary(mod2)
plot(mod2)
rstud = rstandard(mod2)
plot(mod2$fitted.values,rstud)
plot(train_data$x1,rstud)
plot(train_data$x2,rstud)
plot(train_data$x2^2,rstud)

mod3 = update(mod1, .~.+I(sin(x2)))
summary(mod3)
plot(mod3)
rstud = rstandard(mod3)
plot(mod3$fitted.values,rstud) ; abline(h = 0,col=2)
plot(train_data$x1,rstud) ; abline(h = 0,col=2)
plot(train_data$x2,rstud) ; abline(h = 0,col=2)
plot(sin(train_data$x2),rstud) ; abline(h = 0,col=2)

mod4 = update(mod2, .~. +I(x2^3))
summary(mod4)
par(mfrow = c(2,2))
plot(mod4)
rstud = rstandard(mod4)
plot(train_data$x1,rstud) ; abline(h = 0,col=2)
plot(train_data$x2,rstud) ; abline(h = 0,col=2)
plot(train_data$x2^2,rstud) ; abline(h = 0,col=2)
plot(train_data$x2^3,rstud) ; abline(h = 0,col=2)

par(mfrow = c(1,2))
library(MASS)
boxcox(mod4, plotit=T)
boxcox(mod4, plotit=T, lambda=seq(0.5,1.5,by=0.1))

mod5 = lm((y+2.8)^0.8 ~ x1+poly(x2,3), train_data)
summary(mod5)
par(mfrow = c(2,2))
plot(mod5)
rstud = rstandard(mod5)
plot(poly(train_data$x2,3)[,1],rstud) ; abline(h=0, col=2)
plot(poly(train_data$x2,3)[,2],rstud) ; abline(h=0, col=2)
plot(poly(train_data$x2,3)[,3],rstud) ; abline(h=0, col=2)
plot(train_data$x1,rstud) ; abline(h=0, col=2)


mod6 = lm((y+2.8) ~ poly(x1,2)+poly(x2,3), train_data)
summary(mod6)
plot(mod6)
rstud = rstandard(mod6)
par(mfrow = c(2,3))
plot(poly(train_data$x1,2)[,1],rstud) ; abline(h=0, col=2)
plot(poly(train_data$x1,2)[,2],rstud) ; abline(h=0, col=2)
plot(poly(train_data$x2,3)[,1],rstud) ; abline(h=0, col=2)
plot(poly(train_data$x2,3)[,2],rstud) ; abline(h=0, col=2)
plot(poly(train_data$x2,3)[,3],rstud) ; abline(h=0, col=2)
par(mfrow = c(2,1))
boxcox(mod6, plotit = T)


mod7 = lm(y ~ poly(x1,6)+poly(x2,5), train_data)
summary(mod7)
par(mfrow = c(2,2))
plot(mod7)
rstud = rstandard(mod7)
par(mfrow = c(3,2))
plot(poly(train_data$x1,6)[,1],rstud) ; abline(h=0,col=2)
plot(poly(train_data$x1,6)[,2],rstud) ; abline(h=0,col=2)
plot(poly(train_data$x1,6)[,3],rstud) ; abline(h=0,col=2)
plot(poly(train_data$x1,6)[,4],rstud) ; abline(h=0,col=2)
plot(poly(train_data$x1,6)[,5],rstud) ; abline(h=0,col=2)
plot(poly(train_data$x1,6)[,6],rstud) ; abline(h=0,col=2)

plot(poly(train_data$x2,5)[,1],rstud) ; abline(h=0,col=2)
plot(poly(train_data$x2,5)[,2],rstud) ; abline(h=0,col=2)
plot(poly(train_data$x2,5)[,3],rstud) ; abline(h=0,col=2)
plot(poly(train_data$x2,5)[,4],rstud) ; abline(h=0,col=2)
plot(poly(train_data$x2,5)[,5],rstud) ; abline(h=0,col=2)


test_yuka = read.csv("test1.csv")
test_data$y = predict(mod7,test_data[,c(2,3)])
par(mfrow = c(1,1))
plot(test_yuka$X,test_yuka$y, type = "l")
points(test_data$test_id,test_data$y, type = "l", col = 2)


mod9 = lm(y ~ (x1+x2)^4, train_data)
summary(mod9)
